obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.4,-0.4], [-0.4, 0.4], [0.4, 0.4], [0.4, -0.4]]
#robot_radius: 0.4
inflation_radius: 0.5

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: /robot/laser_0, data_type: LaserScan, topic: /robot0/laser_0, marking: true, clearing: true}
